name: list_english_words
description: https://github.com/ALMaclaine/dart_list_english_words.git
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  effective_dart: ^1.2.1
  test: ^1.6.0
